### ISSUE TITLE
Program serialization

### ISSUE THREAD

**Issue by EvolveArt** [lambdaclass/cairo-vm#1183]
**Is your feature request related to a problem? Please describe.**
In Madara we need to compress and base64 encode the `Program` but for that we'd need its bytes representation.

**Describe the solution you'd like**
I guess a simple `to_bytes` method on the `Program` type would do the job.

**Comment by Oppen** [comment]
What is it exactly that Madara does with that encoded representation? Is it long-lived or short-lived? Is it parsed as a the `*.json` or is it the actual memory representation that you want?

**Comment by EvolveArt** [comment]
> What is it exactly that Madara does with that encoded representation? Is it long-lived or short-lived? Is it parsed as a the `*.json` or is it the actual memory representation that you want?


Hey @Oppen, It's short-lived we'd just use it to compress it to base64 as you can see [here](https://github.com/EvolveArt/kaioshin/blob/evolve/fix-to-rpc-class/crates/client/rpc-core/src/utils.rs#L30) (right now there is a `[0]` instead of `program.to_bytes()`

**Comment by Oppen** [comment]
I see in `open-dust`'s fork you use `ProgramJson` to serialize. So, the goal is for it to be the same output as `cairo-compile` would have created, right? I think we can accommodate that.
Related question: who would be the receiver? Is it also something built on top of `cairo-rs`? Because in that case I think we can (later, when the urgency is solved) make a leaner and faster to serialize and deserialize format for transfer.
