### ISSUE TITLE
Use simdjson to deserialize struct

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-vm#1295]
Instead of using the serde library to deserialize programs, use the simdjson library https://github.com/simdjson/simdjson

**Comment by MegaRedHand** [comment]
Opened a PR, but it seems `simdjson` doesn't support parsing arbitrary-sized integers for now (see https://github.com/simd-lite/simd-json/issues/297 and https://github.com/simdjson/simdjson/issues/167)

**Comment by MegaRedHand** [comment]
Blocked until any of the linked issues is resolved.

**Comment by gabrielbosio** [comment]
Reopening since https://github.com/simdjson/simdjson/issues/167 was completed.

**Comment by DiegoCivi** [comment]
Feature [`big-int-as-float`](https://github.com/simd-lite/simd-json?tab=readme-ov-file#big-int-as-float) was added in simd_json, so now arbitrary-sized integers can be parsed. However this is not enough since a lot of information is lost during that parsing. I tried with the following code:
```rust
fn felt_from_number<'de, D>(deserializer: D) -> Result<Option<Felt252>, D::Error>
where
    D: Deserializer<'de>,
{
    let n = simd_json::value::OwnedValue::deserialize(deserializer)?;
    println!("{:?}", n.as_f64());
}
```
I got the following results:
- Case 1:
    - Input: -3618502788666131213697322783095070105623107215331596699973092056135872020481
    - simdjson: -3618502788666131000000000000000000000000000000000000000000000000000000000000
- Case 2:
    - Input: -106710729501573572985208420194530329073740042555888586719234
    - simdjson: -106710729501573570000000000000000000000000000000000000000000
- Case 3:
    - Input: 340282366920938463463374607431768211456
    - simdjson: 340282366920938500000000000000000000000
