### ISSUE TITLE
The memory file format is different from the Python VM one

### ISSUE THREAD

**Issue by odesenfans** [lambdaclass/cairo-vm#1569]
Hello, I am not sure whether this is an actual issue or more of a design choice, but I thought it was worth asking. When comparing the memory files generated by the Python VM and the Rust VM, it appears that the memory files have different formats. Both VMs use a 40-bytes (address, value) pair, but the encoding of each pair is very different.

The Python VM uses the most-significant bit of each value as a relocatable/felt discriminant and also uses a few bits to store the segment (implementation reference [here](https://github.com/starkware-libs/cairo-lang/blob/d61255f32a7011e9014e1204471103c719cfd5cb/src/starkware/cairo/lang/vm/relocatable.py#L73)).

On the other hand, the Rust VM discards the segment information and creates a single vector for all segments, like [this](https://github.com/lambdaclass/cairo-vm/blob/494a4bf0587b30864f33e738e3814482209c5f48/vm/src/vm/runners/cairo_runner.rs#L887). The end result is a flattened view o the memory with all segments written sequentially to a single vector and no apparent means to determine where each segment begins in said vector.

This is annoying to me as it makes comparing VM outputs more complex. As the Rust VM format contains less information than the Python one, I wonder if this new format is a) designed with this intent, or b) a prototype that should be improved. When looking for related issues, I found [this one](https://github.com/lambdaclass/cairo-vm/issues/1446), which results in using the Python VM format for the PIE memory file.  

What is the actual explanation?

**What version/commit are you on?**
88a5bf18900590478b63c65c73ea8f5d60605c41.

**Additional context**
This is related to the porting of the bootloader on the Cairo VM. My goal here is to easily compare the output of the bootloader + different programs on top of both VMs to track discrepancies.

**Comment by Oppen** [comment]
We output the relocated memory. The result after relocation is all `int`s in the Python VM, not `Relocatable`s. See [here](https://github.com/starkware-libs/cairo-lang/blame/caba294d82eeeccc3d86a158adb8ba209bf2d8fc/src/starkware/cairo/lang/vm/memory_dict.py#L227-L228), these two lines are called by `write_binary_memory`.
It could be the case that you find discrepancies because of other known issue (discussed at the time with StarkWare) where the memory is serialized by iterating the `MemoryDict`, which is insertion order, where the Rust VM can't count on that due to different language semantics? The Rust VM uses address order for serialization. At the time it was stated this was an acceptable difference.
You can check if that's the case by using our `memory_comparator.py` script. This solves discrepancies caused by how pairs are ordered.

**Comment by odesenfans** [comment]
Thanks for the explanation and the script, I'll check it out!
