### ISSUE TITLE
can't run cairo1 fibonacci with proof_mode flag

### ISSUE THREAD

**Issue by Retamogordo** [lambdaclass/cairo-vm#1865]
Hola,
I'm trying to follow the readme steps for running the cairo1 basic program.
While I was able to run it as suggested to generate execution trace related outputs:
```sh
cargo run ../cairo_programs/cairo-1-programs/fibonacci.cairo --trace_file ../cairo_programs/cairo-1-programs/fibonacci.trace --memory_file ../cairo_programs/cairo-1-programs/fibonacci.memory
```
when I try to do so in a proof mode:
```sh
cargo run ../cairo_programs/cairo-1-programs/fibonacci.cairo \
--trace_file ../cairo_programs/cairo-1-programs/fibonacci.trace \
--memory_file ../cairo_programs/cairo-1-programs/fibonacci.memory \
--air_public_input=fibonacci_public_input.json \
--air_private_input=fibonacci_private_input.json \
--proof_mode
```
an error is returned:
```sh
Error: IlegalReturnValue
```
I printed out the returned value TypeInfo:
```sh
TypeInfo { long_id: ConcreteTypeLongId { generic_id: GenericTypeId("felt252"), generic_args: [] }, storable: true, droppable: true, duplicatable: true, zero_sized: false }
```
which seems to be a single felt instead array of felts which is apparently expected.

**Comment by FrancoGiachetta** [comment]
Hi @Retamogordo!
Two things on this:

1. As you said, the program you are running returns a felt instead of the array. This is because that program is not meant to be proven. You may want to look at the `serialized_output` folder (inside `cairo-1-programs`). Those programs do return the array it is.

2. You also need to use a different layout, by default `plain` is used (which provides no builtins). If you get the sierra out of the fibonacci.cairo, you'll see that you need `RangeCheck` builtin. So you need at least the `small` layout.

If you want which builtins provide each layout, take a look at this [file](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/types/instance_definitions/builtins_instance_def.rs#L77)

**Comment by FrancoGiachetta** [comment]
I'll close the issue as the solution is the one provided. Ping us if you need anything else!

**Comment by Retamogordo** [comment]
> Hi @Retamogordo! Two things on this:
> 
>     1. As you said, the program you are running returns a felt instead of the array. This is because that program is not meant to be proven. You may want to look inside the `serialized_output` folder (inside `cairo-1-programs`) and search for the fibonacci one. Those programs do return the array that is expected.
> 
>     2. You also need to use a different layout, by default `plain` is used (which provides no builtins). If you get the sierra out of the `.../serialized_output/fibonacci.cairo`, you'll see that you need `RangeCheck` builtin. So you need at least the `small` layout.
> 
> 
> If you want to know which builtins provide each layout, take a look at this [file](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/types/instance_definitions/builtins_instance_def.rs#L77)
> 
> This command should do the trick:
> 
> ```
> cargo run ../cairo_programs/cairo-1-programs/serialized_output/fibonacci.cairo \
> --trace_file ../cairo_programs/cairo-1-programs/fibonacci.trace \
> --memory_file ../cairo_programs/cairo-1-programs/fibonacci.memory \
> --air_public_input=fibonacci_public_input.json \
> --air_private_input=fibonacci_private_input.json \
> --proof_mode \
> --layout small
> ```

Thank you. I definitely omitted the layout specification. Thank you for pointing out the location of provable cairo1 programs.
