### ISSUE TITLE
Implement alias IDs

### ISSUE THREAD

**Issue by Oppen** [lambdaclass/cairo-vm#530]
We're currently using a bit of a dirty hack to allow access to some non-locally-defined types, which is just adding all types by their short names to the hint scope. The correct way is to take note of accessible scopes and IDs of `"alias"` type, looking names into the prior and making the latter store the fully qualified name of the object (type, constant, variable, etc) as its value. This would properly implement the `import` functionality from Cairo as well.

**Comment by fmoletta** [comment]
Each hint has a dictionary of `reference_ids`, mapping  full path name variables to a number that corresponds to a reference in the `reference_manager` field. 
Each hint also has an `accessible_scopes` field determining which scope's variables the hint can access.
If the json file is a properly compiled cairo program, the path of each ids variable should match one of the accessible scopes. 
If this check holds true then there is no reason to use the full path name of a variable instead of its individual name, as we already know we are not accessing any variable beyond the scope of the hint.
Now regarding this last check (that the accessible scopes and reference_ids paths do match). We could add this check during deserialization, but it would worsen the vm's performace to guard the case in which a compiled json file is invalid, in which case our only current guarantee is that the vm doesn't panic.
